---
- name: Install and Configure Internet Information Services (IIS) on Windows Server
  hosts: windows_web_servers
  #become: yes
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: true
        include_management_tools: true
      register: win_feature
    - name: Ensure IIS service is running and set to start automatically
      win_service:
        name: W3SVC
        state: started
        start_mode: auto
    - name: Beacon Trucking Website
      community.windows.win_iis_website:
        name: BeaconTrucking
        state: started
        port: 80
        ip: 127.0.0.1
        hostname: portal.beacon.ky
        application_pool: beacontrucking
        physical_path: C:\inetpub\wwwroot\portal.beacontrucking.ky
        parameters: logfile.directory:C:\inetpub\wwwroot\logs
      register: website
...